name: PurgeEvent
version: 1.0.0
main: me.smughito.purgeevent.PurgeEvent
api-version: 1.19
author: Smughito
description: Dynamic PvP event system with phase-based gameplay
depend: [WorldGuard]

commands:
  purge:
    description: Main command for PurgeEvent
    usage: /purge <start|stop|phase|autophase|reload>
    permission: purge.admin

permissions:
  purge.admin:
    description: Allows access to all purge commands
    default: op
